import { UserPermissions } from '../lib/types';

// Data JSON yang Anda berikan
export const dummyPermissions: UserPermissions = {
  id: 'ebff8a54-b645-4728-8c27-3fd108293f78',
  name: 'Superuser',
  description: 'Role Superuser',
  permissions: [
    // ... (Salin dan tempel SELURUH isi array "permissions" dari JSON Anda di sini) ...
    // Contoh:
    {
      moduleId: 'a9a84ed4-64df-43e0-a2ec-193f26f7bd68',
      moduleName: 'Whitelist',
      functions: [
        {
          id: '5cdabeb2-6add-4c92-aa5b-081982dcbb12',
          name: 'List Whitelist',
          action: 'READ',
          status: true,
        } /* ... functions lainnya ... */,
      ],
    },
    {
      moduleId: 'a9a84ed4-64df-43e0-a2ec-193f26f7bd66',
      moduleName: 'FAQ',
      functions: [
        {
          id: '32534437-5bb0-48e2-a4d5-aed2b5603f8d',
          name: 'List FAQ',
          action: 'Read',
          status: true,
        } /* ... functions lainnya ... */,
      ],
    },
    // ... dan seterusnya untuk semua modul
  ],
};

export const dummyResponseAccessMe = {
  code: 200,
  responseCode: '00',
  responseDesc: 'OK',
  responseData: {
    id: 'ebff8a54-b645-4728-8c27-3fd108293f78',
    name: 'Superuser',
    description: 'Role Superuser',
    permissions: [
      {
        moduleId: 'a9a84ed4-64df-43e0-a2ec-193f26f7bd68',
        moduleName: 'Whitelist',
        functions: [
          {
            id: '5cdabeb2-6add-4c92-aa5b-081982dcbb12',
            name: 'List Whitelist',
            action: 'READ',
            status: true,
            code: 'micro-list-whitelist',
          },
          {
            id: '5cdabeb2-6add-4c92-aa5b-081982dcbb13',
            name: 'Upload Whitelist',
            action: 'CREATE',
            status: true,
            code: 'micro-upload-whitelist',
          },
          {
            id: '5cdabeb2-6add-4c92-aa5b-081982dcbb14',
            name: 'Update Whitelist',
            action: 'UPDATE',
            status: true,
            code: 'micro-update-whitelist',
          },
          {
            id: '5cdabeb2-6add-4c92-aa5b-081982dcbb15',
            name: 'Delete Whitelist',
            action: 'DELETE',
            status: true,
            code: 'micro-delete-whitelist',
          },
        ],
      },
      {
        moduleId: 'a9a84ed4-64df-43e0-a2ec-193f26f7bd66',
        moduleName: 'FAQ',
        functions: [
          {
            id: '32534437-5bb0-48e2-a4d5-aed2b5603f8d',
            name: 'List FAQ',
            action: 'Read',
            status: true,
            code: 'lihat-faq',
          },
          {
            id: 'c3248bbf-b32f-4cc2-8a94-9f69f208fb59',
            name: 'Create FAQ',
            action: 'Create',
            status: true,
            code: 'tambah-faq',
          },
          {
            id: '3f4c3b9a-63b9-4443-8233-1dc927b21f92',
            name: 'Update FAQ',
            action: 'Update',
            status: true,
            code: 'edit-faq',
          },
          {
            id: '8d89a2a1-d7e4-4800-8f1e-3492ed3db41d',
            name: 'Detail FAQ',
            action: 'Delete',
            status: true,
            code: 'detail-faq',
          },
          {
            id: '8d89a2a1-d7e4-4800-8f1e-3492ed3db41c',
            name: 'Delete FAQ',
            action: 'Delete',
            status: true,
            code: 'delete-faq',
          },
        ],
      },
      {
        moduleId: 'fc90d7ba-89a9-4d40-a914-4e7c67f48a8e',
        moduleName: 'Daftar Pengajuan Perpanjangan',
        functions: [
          {
            id: 'e6d05cb4-e88f-4e94-b43c-c846e06fad86',
            name: 'Edit Informasi Usaha Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'edit-informasi-usaha-perpanjangan',
          },
          {
            id: 'a451b02e-f1c1-48c2-b525-2808df1aa3a4',
            name: 'List Perpanjangan Pinjaman',
            action: 'READ',
            status: true,
            code: 'list-perpanjangan-pinjaman',
          },
          {
            id: '506ce181-690a-4fdc-bd5c-4d51830cfa85',
            name: 'Detail Perpanjangan',
            action: 'READ',
            status: true,
            code: 'detail-perpanjangan',
          },
          {
            id: '0ab53455-7309-4ffd-8a22-f1fc65f06888',
            name: 'Unduh Dokumen Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'unduh-dokumen-perpanjangan',
          },
          {
            id: '15b87d47-1f6e-4f36-a259-3178651a787b',
            name: 'History Perubahan Perpanjangan',
            action: 'READ',
            status: true,
            code: 'history-perubahan-perpanjangan',
          },
          {
            id: '999a8fe3-0ebd-4298-a061-3f2d72b30f60',
            name: 'Approve/Reject Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'approve/reject-perpanjangan',
          },
          {
            id: '900282c2-81e1-4039-8a1a-ee4baa8d71d5',
            name: 'Edit Dokumen Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'edit-dokumen-perpanjangan',
          },
          {
            id: 'b1d18168-2afd-40bb-a75e-a6aeb8cd4ee7',
            name: 'Edit Informasi Pendukung Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'edit-informasi-pendukung-perpanjangan',
          },
          {
            id: '35ec1fe7-4357-48b4-b08d-f773a60b887e',
            name: 'Edit Pinjaman Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'edit-pinjaman-perpanjangan',
          },
          {
            id: 'e0c1d59d-0fce-459a-b186-c0bba2b8dfba',
            name: 'Edit Profil Keuangan Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'edit-profil-keuangan-perpanjangan',
          },
          {
            id: '0bc903b3-1c8d-46e0-9943-51891e6712c7',
            name: 'Edit Informasi Pemohon Perpanjangan',
            action: 'UPDATE',
            status: true,
            code: 'edit-informasi-Pemohon-perpanjangan',
          },
        ],
      },
      {
        moduleId: '86b43e51-ccb1-4a95-ba15-ca38a62ff841',
        moduleName: 'Kategory FAQ',
        functions: [
          {
            id: '6facf427-8557-40a0-ba6b-2df232dd81f4',
            name: 'Create Kategori FAQ',
            action: 'CREATE',
            status: true,
            code: 'create-kategory-faq',
          },
          {
            id: '4f00af0c-7251-4770-aad2-87ef9258caaa',
            name: 'List Kategori FAQ',
            action: 'READ',
            status: true,
            code: 'list-kategory-faq',
          },
          {
            id: '0745c047-88d4-4a56-b535-9e8df06ffae6',
            name: 'Detail Kategori FAQ',
            action: 'READ',
            status: true,
            code: 'detail-kategory-faq',
          },
          {
            id: '90ee454f-b1bf-4fc1-9cb5-0575f6b2a487',
            name: 'Update Kategori FAQ',
            action: 'UPDATE',
            status: true,
            code: 'update-kategory-faq',
          },
          {
            id: 'c50fddaf-e575-4c84-84b9-e518f5fb50a4',
            name: 'Delete Kategori FAQ',
            action: 'DELETE',
            status: true,
            code: 'delete-kategory-faq',
          },
        ],
      },
      {
        moduleId: '9782bcc8-bccb-4799-8ab2-297905b54498',
        moduleName: 'Dashboard',
        functions: [
          {
            id: '751dc7fa-96d6-4973-9a15-c7ed3f42eeb2',
            name: 'Analis',
            action: 'READ',
            status: true,
            code: 'dashboard-analisis',
          },
        ],
      },
      {
        moduleId: '9c591b05-0b7b-4c1c-a151-079f17b00794',
        moduleName: 'Activity',
        functions: [
          {
            id: 'c42a0ab8-f075-4011-8f82-8e7ab883cdb8',
            name: 'List Activity',
            action: 'READ',
            status: true,
            code: 'list-activity',
          },
        ],
      },
      {
        moduleId: '9782bcc8-bccb-4799-8ab2-297905b54498',
        moduleName: 'Dashboard',
        functions: [
          {
            id: '9c4e349d-3a4a-4695-83e9-0bcaf83c5976',
            name: 'Rangkuman Pembayaran',
            action: 'READ',
            status: true,
            code: 'dashboard-rangkuman-pembayaran',
          },
          {
            id: '9c4e349d-3a4a-4695-83e9-0bcaf83c5978',
            name: 'Performa Uker',
            action: 'READ',
            status: true,
            code: 'dashboard-performa-uker',
          },
        ],
      },
      {
        moduleId: 'c06a251b-943d-45d6-87b6-ffd52b504328',
        moduleName: 'Monitoring',
        functions: [
          {
            id: '6018e1b8-d460-46db-af35-fb46e5271d77',
            name: 'Detail Monitoring',
            action: 'READ',
            status: true,
            code: 'detail-monitoring',
          },
          {
            id: '6018e1b8-d460-46db-af35-fb46e5271d55',
            name: 'List Monitoring',
            action: 'READ',
            status: true,
            code: 'list-monitoring',
          },
          {
            id: '9446a4f2-3168-4d1c-a5cd-beaf61ccc8ef',
            name: 'List Monitoring Micro',
            action: 'READ',
            status: true,
            code: 'list-monitoring-micro',
          },
          {
            id: 'ed77fb3e-4942-45c0-8c24-d6998ecd4588',
            name: 'Detail Informasi Monitoring Micro',
            action: 'READ',
            status: true,
            code: 'detail-informasi-monitoring-micro',
          },
          {
            id: 'db283cc7-710d-4c38-b41b-1ab5da46251e',
            name: 'Detail Informasi Asuransi Micro',
            action: 'READ',
            status: true,
            code: 'detail-informasi-asuransi-micro',
          },
          {
            id: '2e7c2ad0-b52e-474f-9a62-b38eee92138b',
            name: 'List Transaksi Micro',
            action: 'READ',
            status: true,
            code: 'list-transaksi-micro',
          },
          {
            id: '5cdabeb2-6add-4c92-aa5b-081982dcbb11',
            name: 'Invoice Micro',
            action: 'READ',
            status: true,
            code: 'invoice-micro',
          },
        ],
      },
      {
        moduleId: 'fa791e65-d16d-41e5-8b31-3a4455f92f72',
        moduleName: 'Daftar Pengajuan',
        functions: [
          {
            id: '8d3a9f6f-8967-4f72-8b27-a34f3c539396',
            name: 'List Pengajuan',
            action: 'READ',
            status: true,
            code: 'list-pengajuan',
          },
          {
            id: 'd0445ce4-2dfa-4d45-bda7-9c1d89f31636',
            name: 'Detail Pengajuan',
            action: 'UPDATE',
            status: true,
            code: 'detail-pengajuan',
          },
          {
            id: '62402f47-581a-46dd-ab74-c4f3d6432b84',
            name: 'Unduh Document Prescreening',
            action: 'UPDATE',
            status: true,
            code: 'unduh-document-prescreening',
          },
          {
            id: 'be18e6ce-f1fa-409f-aff4-65e58638fcca',
            name: 'Unduh Document Prefilter',
            action: 'UPDATE',
            status: true,
            code: 'unduh-document-prefilter',
          },
          {
            id: 'ffcf1f47-c1ae-45ad-a15d-0ce31aa20a72',
            name: 'Edit Informasi Usaha',
            action: 'UPDATE',
            status: true,
            code: 'edit-informasi-usaha',
          },
          {
            id: '2b3c61b2-257d-432a-a346-7fa454519256',
            name: 'Edit Informasi Pemohon',
            action: 'UPDATE',
            status: true,
            code: 'edit-informasi-pemohon',
          },
          {
            id: '62dab698-cc79-4e5e-aa7f-bfcc3051602f',
            name: 'Edit Profil Keuangan',
            action: 'UPDATE',
            status: true,
            code: 'edit-profil-keuangan',
          },
          {
            id: 'a42e2ced-ffbb-453e-bc1a-3ee758226f06',
            name: 'Edit Pinjaman',
            action: 'UPDATE',
            status: true,
            code: 'edit-pinjaman',
          },
          {
            id: 'cba2e170-27e9-4a77-8bba-f897eff2e8cf',
            name: 'Edit perjanjian kredit (hak yang berwenang tanda tangan digital)',
            action: 'UPDATE',
            status: true,
            code: 'edit-perjanjian-kredit',
          },
          {
            id: 'ec9c8cc1-ebae-4239-a3fd-b0dd2fc81d4c',
            name: 'History Perubahan',
            action: 'READ',
            status: true,
            code: 'history-perubahan',
          },
          {
            id: '06de84a8-daf1-48c6-9b6f-d703c77e0c7a',
            name: 'Approve/Reject',
            action: 'UPDATE',
            status: true,
            code: 'approve/reject',
          },
          {
            id: '2f55c8cc-b0ac-4443-b6cf-56132f69fad7',
            name: 'Edit Informasi Pendukung',
            action: 'UPDATE',
            status: true,
            code: 'edit-informasi-pendukung',
          },
          {
            id: '454b3a1c-0873-4bc8-a960-4a8c5263b1da',
            name: 'Lihat Informasi Pendukung',
            action: 'READ',
            status: true,
            code: 'lihat-informasi-pendukung',
          },
          {
            id: 'f7fe00f2-cf84-45c2-beaa-331bf8440189',
            name: 'List Pengajuan Micro',
            action: 'READ',
            status: true,
            code: 'list-pengajuan-micro',
          },
          {
            id: '4c72ca87-142e-42a7-8e9f-4ed2eda4b161',
            name: 'Detail Pengajuan Micro',
            action: 'READ',
            status: true,
            code: 'detail-pengajuan-micro',
          },
        ],
      },
      {
        moduleId: 'f4e244d2-2430-48cc-95cb-db8a467f81f5',
        moduleName: 'Daftar Partner',
        functions: [
          {
            id: '6018e1b8-d460-46db-af35-fb46e5271d44',
            name: 'List Partner',
            action: 'READ',
            status: true,
            code: 'list-partner',
          },
          {
            id: '1a916d09-27e3-443a-b7fa-d35043c052e3',
            name: 'Detail Partner',
            action: 'READ',
            status: true,
            code: 'detail-partner',
          },
          {
            id: 'a5ad6c16-a9ce-4ad7-876e-b2a3c076427c',
            name: 'Edit Partner',
            action: 'UPDATE',
            status: true,
            code: 'edit-partner',
          },
          {
            id: '8dec8d93-1eba-4317-8ecc-235508a4c7af',
            name: 'Delete Partner',
            action: 'DELETE',
            status: true,
            code: 'delete-partner',
          },
          {
            id: '955e5d64-c733-4662-93f1-b6c279756e84',
            name: 'Tambah Partner',
            action: 'CREATE',
            status: true,
            code: 'tambah-partner',
          },
        ],
      },
      {
        moduleId: '3a3d8678-045d-407f-9104-dab9a0959914',
        moduleName: 'Daftar Akses',
        functions: [
          {
            id: '9facd745-9e46-4afc-8c05-9fdaa6ec73a9',
            name: 'List Access',
            action: 'READ',
            status: true,
            code: 'list-access',
          },
          {
            id: '27573384-bca8-439d-b60f-51198c6464be',
            name: 'Tambah Access',
            action: 'CREATE',
            status: true,
            code: 'tambah-access',
          },
          {
            id: '5cfd60ed-ab4c-4343-9527-918e20707a37',
            name: 'Detail Access',
            action: 'UPDATE',
            status: true,
            code: 'detail-access',
          },
          {
            id: 'd3ce389c-c912-4667-aef6-ad2005480372',
            name: 'Hapus Access',
            action: 'DELETE',
            status: true,
            code: 'hapus-access',
          },
        ],
      },
    ],
    users: [
      {
        id: '52e7b0a3-d234-49ff-8bf6-dab4ba88821d',
        name: 'Superuser FE',
        email: 'aamridlh@gmail.com',
        personalNumber: '70001084',
        phoneNumber: '088218400204',
        imgUrl: '2602',
      },
    ],
  },
};
